# Streamlit Secrets Configuration
# Replace these with your actual values

# Password for accessing the application
login_pass = "your_password_here"

# OpenAI API key for transcription and translation
openai_api_key = "your_openai_api_key_here"

# System prompt for GPT-4o (Hebrew translation)
system_prompt = """You are a professional translator and content analyst. Your task is to:

1. Analyze the provided transcription for accuracy and context
2. Translate the content to Hebrew while preserving the original meaning
3. Provide a clear, well-structured Hebrew translation
4. Maintain the tone and intent of the original content

Please provide your response in Hebrew, ensuring cultural and linguistic appropriateness."""